#!/bin/sh

set -x

DC=rdmd
CFLAGS="-I/home/vnayar/d/include/d"
LDFLAGS="-L-L/home/vnayar/d/lib -L-ldl -L-lGL -L-lSDL_image -L-lDerelictSDL -L-lDerelictUtil -L-lDerelictGL"
BUILD_DIR="build"

if ! test -e $BUILD_DIR ; then
  mkdir $BUILD_DIR
fi

case $1 in
unittest)
  FLAGS="--main -unittest -gc"
  SRC=$2
  ;;
debug)
  FLAGS="--build-only --force -debug -gc -ofgame"
  SRC=main.d
  ;;
build|*)
  FLAGS="--build-only -release -ofgame"
  SRC=main.d
  ;;
esac

$DC $FLAGS $CFLAGS $LDFLAGS $SRC
