#!/bin/sh

set -x

DC=rdmd
DM_CFLAGS="-I/home/vnayar/d/include/d"
DM_LDFLAGS="-L-L/home/vnayar/d/lib -L-ldl -L-lGL -L-lSDL_image -L-lDerelictSDL -L-lDerelictUtil -L-lDerelictGL"
BUILD_DIR="build"

if ! test -e $BUILD_DIR ; then
  mkdir $BUILD_DIR
fi

case $1 in
unittest)
  TASK_FLAGS="--main -unittest -gc"
  SRC=$2
  ;;
debug)
  TASK_FLAGS="--build-only --force -debug -gc -ofgame"
  SRC=main.d
  ;;
profile)
  TASK_FLAGS="--build-only --force -profile -debug -gc -ofgame"
  SRC=main.d
  ;;
build|*)
  TASK_FLAGS="--build-only -release -ofgame"
  SRC=main.d
  ;;
esac

$DC $TASK_FLAGS $DM_CFLAGS $DM_LDFLAGS $SRC
